### PR TITLE
622 | Incorporating Contributor Covenant Code of Conduct

### LINKED ISSUE #622: Publish community guidelines
As we look to expand the RSE community here in Sheffield it would be useful to have community guidelines in place and available on the website.

The [Contributor Covenant](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) have a useful and reasonable set of guidelines that can be adopted.

### PR DESCRIPTION
**Pull request by ns-rse**
Resolves #622 

As we look to open up and encourage more people to interact with RSE @ TUOS it is prudent to have a Code of Conduct that defines the standards by which we expect people to intereact.

To this end this PR introduces the [Contributor Covenant Code of Conduct](https://www.contributor-covenant.org) to the Community section of the website. On the advice of @bobturneruk this will require sign-off from @mondus before merging, but feedback and approval welcome in the mean time.

Two points...

* I recall recent discussion about the front page and I wasn't sure about whether to make this more prominent on there, but I'm wary of adding clutter and it would likely sit low-down and not be seen. 
* There is `pages/community/asking-for-help.md` which currently isn't included. This is quite an old page, transferred from the old-site in 2018 but has a place holder for `Todo: A brief guide on how to ask for help with research software and data`. I think this page could be a useful place to expand on the different routes and encourage people to join the Slack channel and interact with each other as well as directing to Code Clinics and more formal/longer-term RSE support. Thoughts on this appreciated and a possible new issue to address would be appropriate.

### CODE REVIEW

**Comment by bobturneruk** [comment]
Do you mind if I make some edits to the branch @ns-rse? I think we maybe want another page for Slack that references what you've done (which is great progress).

**Comment by ns-rse** [comment]
Sure go for your life @bobturneruk

**Comment by ns-rse** [comment]
Thanks for adding the necessary navigation @bobturneruk I haven't yet fully understood the site structure.

**Comment by bobturneruk** [comment]
Jekyll is arcane.

**Comment by bobturneruk** [comment]
We'll need to update Slack settings to allow `@sheffield.ac.uk` to auto-join when we merge this.

**Comment by bobturneruk** [comment]
We should also check if we can automate a Slack welcome message, drawing attention to these pages, before merging.

**Pull request merged**
