### PR TITLE
Add afm event

### PR DESCRIPTION
**Pull request by bobturneruk**
Add Bob's talk at "Virtual Data Analysis in Atomic Force Microscopy Meeting"

### CODE REVIEW

**Comment by bobturneruk** [comment]
NB - the abstract has been submitted and approved so will not be changed.

**Review by willfurnass — APPROVED** [review]
Great closing sentence!

**Review by annakrystalli — APPROVED** [review]
LGTM

**Comment by drj11** [comment]
I don't think it needs everyones approval, and I've reviewed the abstract before :). Assuming it renders ok, Good to Go.

**Review by drj11 — APPROVED** [review]

**Comment by bobturneruk** [comment]
Thanks all!

**Pull request merged**
