### PR TITLE
Change BT's position on the team page via the level property

### PR DESCRIPTION
**Pull request by ptheywood**

### CODE REVIEW

**Comment by bobturneruk** [comment]
Maybe I need to fix my bio at this point, too?

**Comment by ptheywood** [comment]
> Maybe I need to fix my bio at this point, too?

Feel free to take over the branch / PR if you want to, or just merge this otherwise

**Comment by bobturneruk** [comment]
I've added some more up to date info. Can you check if it's OK, please @ptheywood? I'm happy to merge.

**Comment by ptheywood** [comment]
Looks good to me. I can't approve this PR given i'm the original author, so i'll just merge it.

**Pull request merged**
