### PR TITLE
Code Clinic: add info re Chrome Remote Desktop

### PR DESCRIPTION
**Pull request by willfurnass**
Addresses #225.

### CODE REVIEW

**Review by bobturneruk — APPROVED** [review]
Looks good.

**Review by annakrystalli — APPROVED** [review]

**Comment by willfurnass** [comment]
Thanks folks.

**Comment by willfurnass** [comment]
We may need to flesh out this info further after trialing Chrome Remote Desktop (something we should do before the next CC sessions).

**Comment by bobturneruk** [comment]
Do you want to give it a test?

**Pull request merged**
