### PR TITLE
Add info. for Magda's bit

### PR DESCRIPTION
**Pull request by bobturneruk**

### CODE REVIEW

**Review by Robadob — APPROVED** [review]
Fine, couple of notes

> written in a Groovy language

Groovy is a programming language, which compiles to Java byte code (some might hence refer to it as a Java dialect afaik). So this reads a bit weird

Also not a fan of the bullet points not starting with caps.

**Comment by bobturneruk** [comment]
Should 
"written in a Groovy language" 
be 
"written in '[Groovy](https://groovy-lang.org/)' (a programming language which compiles to Java byte code)"?

**Comment by Robadob** [comment]
> Should "written in a Groovy language" be "written in '[Groovy](https://groovy-lang.org/)' (a programming language which compiles to Java byte code)"?

That would be better, yes

**Comment by bobturneruk** [comment]
Thanks @Robadob! Very helpful.

**Pull request merged**
