### PR TITLE
Migrate people to a collection

### LINKED ISSUE #66: Migrate Team to a collection
Making team members a colletion may simplify management of that portion of the site. I.e. if a team member leaves to move them to alumni simply change the `alumni` entry in the yaml header.

This would also provide a page per staff member?

### PR DESCRIPTION
**Pull request by ptheywood**
set alumni: true if alumni.
lists are sorted by forenames, surnames and then level, a tier-based system where 0 is most important i.e. Paul.
Individuals now have their own page, i.e. /contact/paul-richmond/ only shows Paul's bio.

Closes #66

### CODE REVIEW

**Comment by drj11** [comment]
this is cool, but `alumni` is a plural form. Can we use `alumnum: true` instead?

**Comment by willfurnass** [comment]
Looks good; Mike C's bio contains borked reference-style Markdown links though.

**Comment by willfurnass** [comment]
Also, think it would look better if people's names were `<h2>` rather than `<h1>`.

**Review by willfurnass — COMMENTED** [review]
See comments

**Comment by ptheywood** [comment]
I've addressed the changes discussed above.

**Comment by willfurnass** [comment]
Thanks @ptheywood !

**Pull request merged**
