### PR TITLE
Update Adam's alumnus status

### PR DESCRIPTION
**Pull request by twinkarma**
@bubblecontrol anything you'd like to update on your profile?

### CODE REVIEW

**Review by ns-rse — APPROVED** [review]
:+1:

**Review by bubblecontrol — DISMISSED** [review]
Thanks! Sorry way away for two weeks!

**Comment by bubblecontrol** [comment]
Just checked again - properly 🙄 - probably should update some bits on the profile. I'll do it before the end of the week.

**Review by bubblecontrol — APPROVED** [review]

**Comment by twinkarma** [comment]
Thanks for updating the bio @bubblecontrol !

**Pull request merged**
