### PR TITLE
Pagination

### PR DESCRIPTION
**Pull request by Robadob**
I recovered some/all the changes from #154 for pagination.

It appears I'm missing the commit which added manual separator to all old blogposts (I presumably never pulled that update to my laptop before overwriting remote, it will exist on my desktop in Sheffield but I don't currently have access to that).

Demo here: https://rse-mirror.robadob.org/blog/

From the previous PR:

> To manage this, you need to additionally include `excerpt_separator: <!--more-->` in the front matter, and then place your separator (e.g. `<!--more-->`) somewhere in the body of your post. Everything above that separator will appear above the fold. If this isn't included, it appears to simply treat the first blank line as the separator.

### CODE REVIEW

**Comment by bobturneruk** [comment]
- ~~Some posts are reiterated in full.~~
- ~~Some recent posts need a manual separator.~~
- Post headings should be smaller.

**Comment by Robadob** [comment]
> Some posts are reiterated in full.

This page (and maybe others?) specify the excerpt separator, but don't use it. So the fold on first line-break is not applied.
https://rse-mirror.robadob.org/blog/2020-09-03-agile/

(Repo search confirms there are 8 blog posts with excerpt separator, the above is the only one using it incorrectly).

**Comment by willfurnass** [comment]
Looks good.  Agree with @bobturneruk re the heading size.  Also, as mentioned in person, would be good to have similar blurb per post beneath blog titles on the homepage.

**Comment by twinkarma** [comment]
The heading size should be fixable by adding some class to the container that wraps around all the blog post listings e.g.

```xhtml
<div class="my-blog-container">
  ... all the blog articles here
</div>
```

and in the css you'd use a child selector to specifically change h1 font size e.g.

```css

.my-blog-container h1{
  font-size: 1rem !important;
}

```

**Comment by ptheywood** [comment]
It's best to not use `!important` in css, it can break accessibility related features. Instead using a more specific css rule, or placing the rule at the correct location in the style sheet heirarchy is preffered. 

the current `h1` style comes from the rule is only specific to `h1` elements, so anything more than that would be more specifc (i.e. the `!important` is not required in teh above example). 

In general the post heading size is consistent with all other headings on our site, in which case adjusting the sizes of all `h*` elements (and `.h*` classes) to just scale them down a little would be the more appropriate fix.

**Comment by Robadob** [comment]
The branch should be changeable by anyone with write access to this repo, so feel free ;)

**Comment by Robadob** [comment]
Ok, I've wrapped the except insert in the css class `blog-excerpt` https://github.com/Robadob/RSE-Sheffield.github.io/blob/353767701335699aec3eba2b1fd0a2400660e68b/blog/index.html#L24

Looking at this I see the problem again.

The page title is H1.
We want to display the blog post title as H2 (I have now changed this, it was H1).
The blog post excerpts themselves may contain `#` markdown elements, which would be rendered at H2, but we want to force them to be rendered as H3.

**Comment by Robadob** [comment]
```html
<div class="blog-excerpt">
    <h2>foo</h2>
</div>
<h3>bar</h3>
```

The question is how to use css to make `foo` look like `bar`. I've no idea how to dynamically do this (so it doesn't need to be changed if the site theme is updated), and playing with browser dev tools suggests the sizes for h values come from `assets/plugins/scss/_type.scss`, but that file doesn't even exist in the repo.

```
h1, .h1 { font-size: $h1-font-size; }
h2, .h2 { font-size: $h2-font-size; }
h3, .h3 { font-size: $h3-font-size; }
h4, .h4 { font-size: $h4-font-size; }
h5, .h5 { font-size: $h5-font-size; }
h6, .h6 { font-size: $h6-font-size; }
```

*(If no one can suggest how to do this, I'll write some JS to fix it, I can do proper code)*

**Comment by ptheywood** [comment]
I think they come from bootstrap, and browsers can effectively de-compile a css file back into sass/scss source for more useful info in dev tools (via `.css.map` I think but not 100%). 

i.e. in `assets/plugins/bootstrap/css/bootstrap.min.css` it contains `.h1,h1{font-size:2.5rem}.h2,h2{font-size:2rem}.h3,h3{font-size:1.75rem}`

Looks like the general themeis based on [devAid](https://themes.3rdwavemedia.com/bootstrap-templates/startup/devaid-free-bootstrap-theme-for-developers-side-projects/). To edit bootstrap we'd need to pull it inourselves and hook up the sass/scss gen process.

Or instead, we can just tack on some size overrides after the bootstrap file is included. to make sure they are updated together in the future, either do this via sass/scss, or be lazy and just duplicate the rules with the current literal values.

So chuck this in `assets/css/custom.css` and adjust things as you see fit. 
```
/* Sizes for h1 to h6, overriding bootstrap css */
h1, .h1 { font-size: 2.5rem; }
h2, .h2 { font-size: 2rem; }
h3, .h3 { font-size: 1.75rem; }
h4, .h4 { font-size: 1.5rem; }
h5, .h5 { font-size: 1.25rem; }
h6, .h6 { font-size: 1rem; }
/* Adjust heading sizes for blog-excerpts */
.blog-excerpt h1, .blog-excerpt .h1 { font-size: 2rem; }
.blog-excerpt h2, .blog-excerpt .h2 { font-size: 1.75rem; }
.blog-excerpt h3, .blog-excerpt .h3 { font-size: 1.5rem; }
.blog-excerpt h4, .blog-excerpt .h4 { font-size: 1.25rem; }
.blog-excerpt h5, .blog-excerpt .h5 { font-size: 1rem; }
.blog-excerpt h6, .blog-excerpt .h6 { font-size: 1rem; } / * No h7 to steal a size from */
```

**Comment by Robadob** [comment]
https://rse-mirror.robadob.org/blog/

I've applied @ptheywood 's fix and created a test post on my mirror.

`# This post is not present in the PR` is now the same size as the post title, but I vaguely remember we aren't supposed to use single `#` inside blog posts anyway.

**Comment by ptheywood** [comment]
From the [MDN on heading element usage notes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements#usage_notes): 

> + Heading information can be used by user agents to construct a table of contents for a document automatically.
> + Avoid using heading elements to resize text. Instead, use the CSS font-size property.
> + Avoid skipping heading levels: always start from `<h1>`, followed by `<h2>` and so on.
> + Use only one `<h1>` per page or view. It should concisely describe the overall purpose of the content.
> + Using more than one `<h1>` will not result in an error, but is not considered a best practice. Using only one `<h1>` is beneficial for screenreader users, and SEO.
> + While HTML5 allows a `<h1>` per sectioning element, it is not considered best practice, and may subvert the expectations of how screen reader users navigate.

So it's not best practice but is not striclty bad to use multiple H1's per page. The main thing is to not skip levels as that might break accessibility tools

> A common navigation technique for users of screen reading software is jumping from heading to heading to quickly determine the content of the page. Because of this, it is important to not skip one or more heading levels. Doing so may create confusion, as the person navigating this way may be left wondering where the missing heading is.

We could potentialyl find a way to set the markdown render used by jekyll (kramdown?) to start at `h2` instead of `h1`, using the `header_offset` parameter. I'm not sure how to apply this to just blog posts though rather than setting it universally for all rendering  (although i've not really looked).

**Comment by Robadob** [comment]
> So it's not best practice but is not striclty bad to use multiple H1's per page. The main thing is to not skip levels as that might break accessibility tools

It's more an observation that using `# heading` in a blog post, gives it the same style as the title of the blog post. Which feels dirty.

> We could potentialyl find a way to set the markdown render used by jekyll (kramdown?) to start at h2 instead of h1, using the header_offset parameter. I'm not sure how to apply this to just blog posts though rather than setting it universally for all rendering (although i've not really looked).

This would then mean all old blog posts need updating?

**Comment by Robadob** [comment]
Anyway, based on it's current state in demo. The issues outlined by @bobturneruk @willfurnass are resolved?

**Comment by twinkarma** [comment]
It's probably better to just put `exerpt_separator ` in `_config.yml` rather than in all the our post and collection files?

**Comment by Robadob** [comment]
If we specify it at a global level, we would need to update all historic blog posts, otherwise their entire articles are likely to sit above the fold.

Specifying it per blog post has better default behaviour for a missing seperator (it treats first line-break as the fold)

**Comment by Robadob** [comment]
(I also don't think I was aware that was an option)

**Comment by Robadob** [comment]
Could also be argued, that having it prominently in the header of each article, will remind people to place it/write their posts with it in mind.

**Comment by bobturneruk** [comment]
@Robadob - what's the best way to test this out? Do I need a copy of your fork r have you a build online?

**Comment by Robadob** [comment]
My mirror should be upto date with the branch. I think it just has 2 extra commits, one to direct it at my mirror domain and another with a headings test post.

https://rse-mirror.robadob.org/blog/

**Comment by bobturneruk** [comment]
Should we see breaks on the homepage? https://rse-mirror.robadob.org/

**Comment by Robadob** [comment]
I haven't made any changes to the homepage, someone else was doing a PR for homepage changes (https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/issues/450). I haven't rebased upstream in the past week, so the mirror is probably a week or two behind.

**Review by bobturneruk — APPROVED** [review]
I think this is an improvement - please add instructions for using `<!--more-->` to the readme.

**Comment by twinkarma** [comment]
@Robadob I'm actually waiting for you to finish this PR first before doing mine since you'd already started on this before me.

**Comment by Robadob** [comment]
@twinkarma It is/was finished, I was expecting @willfurnass to review it, but I guess he's been busy (would have raised it at the next c&t meeting). I'll do bob's change in the next couple of hours and then get it merged.

**Comment by Robadob** [comment]
Have made bob's changes, rebased and squashed the commits. This can be merged once CI passes.

I couldn't spot a related issue to close.

I also updated the mirror to have the unsquashed commits and latest upstream rebase (but that's only in my `gh-pages` branch, so will get nuked eventually when I next work on a feature requiring the mirror).

**Comment by willfurnass** [comment]
@Robadob - sorry for not responding before now.  https://rse.shef.ac.uk/blog looks good but we don't have the same logic on https://rse.shef.ac.uk/blog/all, which is linked to from each blog post.

**Comment by Robadob** [comment]
> @Robadob - sorry for not responding before now. https://rse.shef.ac.uk/blog looks good but we don't have the same logic on https://rse.shef.ac.uk/blog/all, which is linked to from each blog post.

Ah, I wasn't aware of that page.

Presumably /all can be nuked now and redirect to the blog home?

**Edit:** Oh appears I added that link (18 months ago), so must have been aware of it at some point.

**Comment by willfurnass** [comment]
Yeah, we ideally want just one full index of blog posts.

**Comment by Robadob** [comment]
I'll try and sort it when I get a minute.

**Pull request merged**
