### PR TITLE
Add newsletter

### PR DESCRIPTION
**Pull request by bobturneruk**
Adds newsletter section to site, initial newsletter.

### CODE REVIEW

**Review by twinkarma — APPROVED** [review]
Looks sensible to me

**Comment by bobturneruk** [comment]
Thanks @twinkarma - plan is not to merge until newsletter content is done.

**Comment by bobturneruk** [comment]
I should change this to use collections.

**Review by ptheywood — COMMENTED** [review]
Collection based implementation is working nicely. 

There is an issue with the navigation bar at certain horizontal resolutions, where it overlaps onto 2 rows rather than folding down to the mobile nav. 


Either need to reduce the total number of top level items, or change the breakpoint for navigation compaction. 

image


The easiest solution is probably to just fold newsletter into the RSE Community heading?
The PR to add the uni logo to the navbar would probably exacerbate this (and might need fixing independantly regardless)

**Comment by bobturneruk** [comment]
Thanks @ptheywood and @twinkarma - maybe worth considering in relation to https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/pull/257. The whole RSE Community section needs review as well. This may change the headings / organisation thereof.

**Comment by bobturneruk** [comment]
Community section review now https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/issues/264

**Comment by bobturneruk** [comment]
I've added newsletter content.

**Review by davidwyld — APPROVED** [review]

**Comment by bobturneruk** [comment]
- EPSRC webinar

**Comment by bobturneruk** [comment]
- EPSRC webinar

**Comment by willfurnass** [comment]
Maybe worth mentioning that Fariba is part of TUOS ML group.

**Comment by bobturneruk** [comment]
Following the general approval and incorporation of comments from yesterdays training meeting (20200701), I'm merging. Email out to Google list will follow.

**Pull request merged**
