### PR TITLE
Add currently available details of Research Computing @ Sheffield to events

### PR DESCRIPTION
**Pull request by bobturneruk**

### CODE REVIEW

**Comment by Robadob** [comment]
Rob's talk title:  'Accelerating the modelling of tumour growth using GPUs: lessons learned'

**Review by Robadob — COMMENTED** [review]
I'm happy.
Is there still no official website/page for the event you could link out to?

**Comment by bobturneruk** [comment]
Ta @Robadob. Doesn't seem to be. I'd like @willfurnass to OK this and merge it if he's happy, too.

**Review by willfurnass — APPROVED** [review]
LGTM.  Can link to official conference info inc abstracts when it goes online (Issue #214)

**Comment by bobturneruk** [comment]
This has failed to build.

**Comment by willfurnass** [comment]
@bobturneruk Able to build locally.  Suspect GitHub's Jekyll setup is playing catch-up.

**Pull request merged**
