### PR TITLE
Add code clinic all to action button

### PR DESCRIPTION
**Pull request by bobturneruk**
I think this is adequate, but I'd appreciate improvements.

### CODE REVIEW

**Comment by bobturneruk** [comment]
image

**Review by annakrystalli — COMMENTED** [review]
Nice idea! 

Only thing is, I'm not sure it's clear enough that it's an action button and not just different formatting. Maybe starting with a verb (eg "Book a Code Clinic" with _get help from an RSE_ as a smaller subtitle would make it clearer?

I also thing a larger margin around the text might help and also would look more appealing.

**Comment by Robadob** [comment]
Yeah I think Anna's right, it doesn't look clickable, it could be an
unusual page title (though that might be flat-ui styling's fault).

**Comment by bobturneruk** [comment]
image
Sufficiently better? Worse?

**Comment by Robadob** [comment]
https://www.nngroup.com/articles/clickable-elements/

> Static items should not have the same color as hyperlinks.

That might be part of the issue.

Additionally, making "Book a Code Clinic" underlined (albeit conflicting with the entire site style) would be a big signifier that it's clickable.

**Comment by drj11** [comment]
Looks good.

There are possible issues with a `text-align: center` being required, but I'd have to look at the CSS itself to be sure, and it's a fairly minor issue anyway. Merge at will.

**Review by drj11 — APPROVED** [review]

**Comment by ptheywood** [comment]
Using an image as the body for a link is generally poor from an accessibility front, plus I'm not sure how this will look at narrow resolutions (mobile) currently. 
At the very least the `alt` attribute of the image needs to include the included text. 
Using `:hover` based styling too (via css on anchor tags, rather than an image) will make it appear more clickable too. 
As we use Bootstrap we should be able to leverage `.btn .btn-success` to get a green button which is more accessible without too much issue (give me a few mins).

**Comment by ptheywood** [comment]
My suggestion would be:

```
            <a href="https://goo.gl/forms/5MVy0jM6xQhWlpmn1" class="btn btn-success" style="font-weight:normal; white-space: normal;">
                <strong>Book a Code Clinic</strong>: Get help from an RSE
            </a>
```

This provides `:hover` styling which changes the colour of the element, indicating it's clickable:

image
image



On an Iphone: 
image

On a 1200px wide screen (arbitrary resolution above ~1000px, which just shows the fact I was doing webdev 10 years ago...) :
image

The class `btn` applies generic bootstrap button styling, and `btn-success` makes it green (in our case). 
Optionally `btn-sm` and `btn-lg` could change the size if desired (with minimal effort). 

`.btn` makes the font weight bold (which you typically want in buttons), but to have multiple I've added the inline style of `font-weight:normal`. Would be better in a .css file but this was less effort (and specific). 
`white-space:normal` allows it to line break, for small devices.

**Comment by bobturneruk** [comment]
Thanks @ptheywood - would you push that change, please? I'm far from an expert at this stuff - most of my skills are from the 90s.

**Comment by bobturneruk** [comment]
Thanks @ptheywood!

**Comment by drj11** [comment]
having @ptheywood and @annakrystalli comment is like having magic fairies making it better. it's great!

**Comment by bobturneruk** [comment]
Shall I merge?

**Comment by annakrystalli** [comment]
LGTM! Go for it @bobturneruk !

**Review by annakrystalli — APPROVED** [review]

**Comment by bobturneruk** [comment]
Thanks for all your input!

**Comment by drj11** [comment]
Pleasingly short time from suggestion to live on the web!

**Pull request merged**
