### PR TITLE
Add Plausible Analytics

### PR DESCRIPTION
**Pull request by bobturneruk**
This enables https://plausible.io/ for rse.shef.ac.uk. If you'd like an invite to be an Admin and have not received one, please let me know. Plausible claims:

> ...No cookies and fully compliant with GDPR, CCPA and PECR.

If anyone sees a hint of a problem with this, I'd like to hear about it, please!

### CODE REVIEW

**Comment by bobturneruk** [comment]
I am clear to pay for the full version for a year.

**Comment by drj11** [comment]
this is great, good job finding plausible.io

**Comment by bobturneruk** [comment]
Thought you'd like!

**Review by davidwyld — APPROVED** [review]
LGTM!

**Pull request merged**
