### PR TITLE
Auto assign issues to rse-website-development project

### PR DESCRIPTION
**Pull request by twinkarma**

### CODE REVIEW

**Comment by bobturneruk** [comment]
I thought there was a way of doing this without a GH action, but this looks good!

**Comment by Robadob** [comment]
> I thought there was a way of doing this without a GH action, but this looks good!

I think you can automate moving them along the project board, but initially adding them to the project seems to be manual.

image

**Comment by ptheywood** [comment]
The new gh projects (non-classic, so would need a new board) recently added this as a default feature in the workflows settings

image

https://docs.github.com/en/issues/planning-and-tracking-with-projects/automating-your-project/adding-items-automatically

We can probably close this PR, and closes the unused existing board or migrate it to the non-classic project board and enable the auto-add feautre?

**Comment by ptheywood** [comment]
Board now migrated to the new projects system, and automatic adding of open issues and pr's (matching this PR) has been enabled. 

https://github.com/orgs/RSE-Sheffield/projects/9/views/1

Also enabled auto-archive, so once closed for 2 weeks any board items will be archived.

**Pull request closed without merging**
