### PR TITLE
Add git and github training

### PR DESCRIPTION
**Pull request by bobturneruk**

### CODE REVIEW

**Review by Robadob — COMMENTED** [review]
> `title: "git & GitHub through GitKraken - from Zero to Hero!"`

----------------

> ## How can we effectively work together on the same code? 

> **This event covers essential information for research teams collaborating on software.**


Is the event aimed at git in general, or collaboration with git? Might be worth tweaking the title to imply collab if that's the intended purpose, or better phrase the intro to not exclude anyone who wants to learn git for non-collab work.

**Comment by bobturneruk** [comment]
@Robadob it's to go from no git to being able to collaborate via github. It's not intended for solo git, but will equip those skills (as they're also needed for collaboration). Does the description make sense in light of this?

The title is fixed.

**Comment by Robadob** [comment]
> @Robadob it's to go from no git to being able to collaborate via github. It's not intended for solo git, but will equip those skills (as they're also needed for collaboration). Does the description make sense in light of this?

It feels a tad exclusionary to anyone not needing to collaborate on code imminently.


Something more like this might be clearer.

~"This is an introductory course, teaching the git skills required to manage research code over it's development lifecycle. These skills are essential for collaborative research teams."

**Comment by bobturneruk** [comment]
Cheers again @Robadob - I feel there is definitely room for a "pure `git`" training course. Again, we're doing what we can now, hopefully as a foundation to do more in future.

**Comment by Robadob** [comment]
Even working a large solo project, it's not uncommon to have multiple concurrent feature branches (e.g. start working on something, then get blocked or priorities change). So the skills to work with them solo are exactly the same as collab imo.

**Comment by bobturneruk** [comment]
Thanks for the feedback - I dispute it though 😄 - there is a huge social aspect to collaborating with github + technical stuff around use of issues, PRs, CI + policy stuff like code formatting standards, contributing guidelines. Ultimately this course won't be for everyone - we're not able to offer a full curriculum that covers the broad spectrum of training needs at present. I hope to have your ongoing engagement at feedback as we try and build this up.

**Pull request merged**
