### PR TITLE
Re-enable link checking in Travis CI jobs with htmlproofer

### PR DESCRIPTION
**Pull request by willfurnass**
As discussed in #239 with @twinkarma

### CODE REVIEW

**Comment by willfurnass** [comment]
Urgh.  Now, what combination of `htmlproofer` args yield something useful if in the first instance we're just wanting to check internal links are valid?

**Comment by willfurnass** [comment]
Current thoughts: something like

```sh
bundle exec htmlproofer \
    --file-ignore="/\/node_modules\//" \
    --checks-to-ignore=ScriptCheck,ImageCheck \
    --disable-external \
    --internal-domains shef.ac.uk,sheffield.ac.uk,insigneo.org \
    --alt-ignore=assets/* \
    --allow-hash-href \
    _site 
```

Still not quite right though.

**Comment by ptheywood** [comment]
The state as of 27eab6e looks almost right. 

Several of the links it's still testing as internal but should be external is because they are specified without a protocol. i.e. 
```
<a href="www.instancehub.com">InstanceHub</a>
```
is missing `https://` (or `http://` if https is unavailable, or `//` to use matching protocol)

I'm unsure about why some internal links such as `/training/workshop/2020-07-27-gpu-hackathon-2020` are being reported as invalid, as it appears valid to me. 

One issue might be with any links to other repos in our org with gh-pages branches. I'm not sure how that would be resolved. I.e. `https://rse.shef.ac.uk/uos-hpc-resources-presentation/#/` maps to the `https://github.com/RSE-Sheffield/uos-hpc-resources-presentation` repo, rather than part of this repo.

**Comment by willfurnass** [comment]
Some of those issues will be fixed by rebasing on the branch where I've fixed several links (PR #76); I'll do that now.

I think the problem with /training/workshop/2020-07-27-gpu-hackathon-2020 as a link target is that the rendered file on disk is /training/workshop/2020-07-27-gpu-hackathon-2020.html. JS magick somewhere?

**Comment by ptheywood** [comment]
The aliasing of `.html` is usually done server side .htaccess or similar. gh pages seems to support this and I'd have assumed that the jekyll built in server does. I would have expected more of the internal links to use that format (i.e. `/blog/` in the main navigation)

**Comment by ptheywood** [comment]
I'm currently unable to install the html-proofer gem locally (ubuntu 1804, ruby 2.5.0) because one of the dependency gems cannot be instlaled 

```
An error occurred while installing nokogumbo (2.0.2), and Bundler cannot
continue.                                                                                 
Make sure that `gem install nokogumbo -v '2.0.2' --source 'https://rubygems.org/'`        
succeeds before bundling.     
```

Which is due to 

```
/usr/lib/ruby/2.5.0/rubygems/dependency.rb:312:in `to_specs': Could not find 'nokogiri' (=
1.8.2) - did find: [nokogiri-1.10.9,nokogiri-1.10.0] (Gem::MissingSpecVersionError)
```

Looks like CI passes because it uses ruby 2.3.1?

**Comment by willfurnass** [comment]
Superseded by #320

**Pull request closed without merging**
