### PR TITLE
Add information on past and current projects

### PR DESCRIPTION
**Pull request by bobturneruk**
Currently getting this error:
```
bundle exec jekyll serve
```
...
```
Liquid Exception: Liquid error (line 3): Cannot sort a null object. in pages/service/projects/projects.md
```

### CODE REVIEW

**Comment by bobturneruk** [comment]
Error resolved by not using Windows 10.

**Comment by bobturneruk** [comment]
I'd like @willfurnass or @mondus to approve this, please, as it's a change to what the team communicates with the outside world.

**Comment by Robadob** [comment]
I've updated the mirror. https://rse-mirror.robadob.org/service/projects/

In my opinion, having such large headings for project names (and a subheading saying 'Project Description') doesn't work very well when there's only 1-2 lines of body per project.

Need to reconsider how to lay it out.

**Comment by Robadob** [comment]
I also expect we would want to add more projects, rather than it simply being your portfolio before it joins the main site.

**Comment by bobturneruk** [comment]
Thanks @Robadob . Do you think I need to fiddle with CSS to make the headings smaller? I thought I'd merge then let others branch and add. I should probably put "work in progress" at the top of I do that?

**Review by davidwyld — APPROVED** [review]
Looks great, nice one. Maybe we can refine later but this is a good starting point.

**Comment by Robadob** [comment]
> Do you think I need to fiddle with CSS to make the headings smaller?

Replace the project name  headings with the same heading level as Project description.
Remove all of the project description headings, and move the project description text to the first item after project name.
Maybe also forcibly put the standalone UKRI links on a separate line rather than having them trail the body text.

> thought I'd merge then let others branch and add. I should probably put "work in progress" at the top of I do that?

You made the branch inside the repository, so anyone could commit directly to the branch, or make PRs directly to the branch. That or grab a list of projects/people off Pauls project management website and leave body for each as tbd. Bit cleaner than under construction imo.

**Comment by bobturneruk** [comment]
Better layout @Robadob?

**Comment by bobturneruk** [comment]
I've added a few more projects, but I've realised I'm going to need to ask people to add projects they're familiar with or it will take forever and I'll mess things up. If the layout's now OK and @willfurnass and @mondus are happy with the approach, I'd encourage others to either commit to this branch or PR as @Robadob suggests.

**Comment by bobturneruk** [comment]
I aspire to make my project descriptions a bit longer.

**Comment by Robadob** [comment]
I've updated the mirror and I think it looks better. I'd still prefer the description to be the first item under each heading though (seems most relevant).

For PRIMAGE you could add.

> The PRIMAGE project is EU collaboration which aims to develop a cloud platform for decision support in the clinical management of two paediatric cancers. Sheffield RSE has reimplemented a python model, in high performance CUDA, in parallel with the python model's development. This has enabled the modelling of larger tumours and faster parameter searching.

Paul is considered a PI on the project, so he might need to be named too.

**Comment by willfurnass** [comment]
@bobturneruk Looks good.

Do we want to decide on a minimal structure per post before going any further?  

Might also be useful to decide on a minimal set of headers.  I think having a mandatory start date and an optional end date could be useful: would no longer need to explicitly label projects as being active or not.

I did draft a simple schema for a public portfolio of projects a while back but am damned if I can find it now...

**Comment by willfurnass** [comment]
Also, we might want to merge new per-project content into a new 'projects' branch until we have enough content to want to merge that into master.

**Comment by Robadob** [comment]
> Do we want to decide on a minimal structure per post before going any further?

It would probably be worthwhile to emphasise the value we add to each of the projects, rather than simply describing the purpose of each project. As presumably this page will exist to market what we can offer to other projects.

**Comment by bobturneruk** [comment]
Thanks @Robadob and @willfurnass. All of your points are good.

Re...  
> I think having a mandatory start date and an optional end date could be useful: would no longer need to explicitly label projects as being active or not.

I wasn't up for figuring out date comparisons in whatever language Jekyll is!

Generally, there's a trade off between getting the content up, and waiting until it's "right". I suggest we discuss this on Wednesday in the team meeting.

**Comment by bobturneruk** [comment]
Inspiration https://nclrse.blob.core.windows.net/public/nclrse-2020-public.pdf

**Comment by bobturneruk** [comment]
I've changed this so we have a csv file which lists all funded projects and metadata, but the project is only listed if it has an accompanying description in markdown. I'd be interested in feedback on this (experimental) approach. The next step will be to produce example description with guidance, and to expand the metadata in the csv.

**Comment by willfurnass** [comment]
I like this approach.

Need to have a way of robustly reproducing the CSV inc maintaining persistent primary keys per project if we're to link against that from other places.  The following SQL gives us something like that CSV when run against our RSEAdmin database (sans the tools/methods tags and short name per project):

```sql
SELECT 
    p.ID, 
    p.name, 
    min(p.start) AS p_start,
    max(p.end),
    cl.department, 
    array_agg(distinct concat(u.first_name, ' ', u.last_name))
FROM 
    rse_project AS p 
    LEFT JOIN rse_client AS cl ON p.client_id = cl.id 
    LEFT JOIN rse_rseallocation AS a ON p.id = a.project_id 
    LEFT JOIN rse_rse AS r ON a.rse_id = r.id
    LEFT JOIN auth_user AS u ON r.user_id = u.id
WHERE 
    p.status = 'F'
GROUP BY
    p.ID,
    p.name, 
    cl.department
ORDER BY 
    p_start DESC
;
```

Which could be made a standard report in RSEAdmin.

Things that I think need sorting:
 - [ ] Link project descriptions and CSV rows by integer project ID for unambiguous cross referencing with RSEAdmin
 - [ ] Move list of tags into per-project .md files so won't be overwritten if regenerate CSV
 - [ ] Flesh out list of tags and descriptions for more projects
 - [ ] Contribution docs and template .md project
 - [ ] Allow for nicer title (public-friendly) to be specified in .md files 

Then later:
 - [ ] Search/filter by tag
 - [ ] Search/filter by team member
 - [ ] Link to profiles of team members
 - [ ] Handle aesthetics using divs/spans and CSS.

**Comment by bobturneruk** [comment]
Thanks @willfurnass. The technical approach is sound, but I think automated links between RSE admin and the website are probably overkill as there's a bunch of manual editing (deleting boring projects and adding metadata needed). The point of the `.csv` file was mostly to make it quick and easy to bulk edit project metadata and enable projects to be displayed when a description is added. We need to make this task as light and easy as possible or it will take forever (people have little time and seem to hate doing this stuff)! For the number of project we have funded, keeping rseadmin and website in sync. manually would be fine.

**Comment by willfurnass** [comment]
Yes, you're right about a pragmatic approach being appropriate right now.   

I've added a list of unique methods/tech tags at the top of the page.

**Comment by bobturneruk** [comment]
I'm getting a warning now:

```
bob@DESKTOP-T21K8IM:~/RSE-Sheffield.github.io$ bundle exec jekyll serve
Configuration file: /home/bob/RSE-Sheffield.github.io/_config.yml
            Source: /home/bob/RSE-Sheffield.github.io
       Destination: /home/bob/RSE-Sheffield.github.io/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
/home/bob/RSE-Sheffield.github.io/vendor/bundle/ruby/2.7.0/gems/jekyll-3.9.0/lib/jekyll/readers/data_reader.rb:57: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/usr/lib/ruby/2.7.0/csv.rb:714: warning: The called method `read' is defined here
       Jekyll Feed: Generating feed for posts
    Liquid Warning: Liquid syntax error (line 22): [:pipe, "|"] is not a valid expression in "{{ all_tags | sort_natural | uniq: | join: " &middot; " }}" in pages/service/projects/projects.md
                    done in 3.667 seconds.
/home/bob/RSE-Sheffield.github.io/vendor/bundle/ruby/2.7.0/gems/pathutil-0.16.2/lib/pathutil.rb:502: warning: Using the last argument as keyword parameters is deprecated
                    Auto-regeneration may not work on some Windows versions.
                    Please see: https://github.com/Microsoft/BashOnWindows/issues/216
                    If it does not work, please upgrade Bash on Windows or run Jekyll with --no-watch.
 Auto-regeneration: enabled for '/home/bob/RSE-Sheffield.github.io'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
```

**Comment by willfurnass** [comment]
Warning fixed and added info on ITS HPC project.

**Pull request merged**
