### PR TITLE
Enable social cards

### LINKED ISSUE #178: Social Media Cards (Open Graph)
Blog posts (and website pages in general?) don't currently produce a social media card when linked in tweets etc.

This might be nice for sharing blog posts. 

Open Graph looks like twitter and facebook support it (along with other specific `<meta>` tags. 

This should be done for blog posts at a minimum.

### PR DESCRIPTION
**Pull request by davidwyld**
Resolves https://github.com/RSE-Sheffield/RSE-Sheffield.github.io/issues/178

### CODE REVIEW

**Review by Robadob — DISMISSED** [review]

**Review by ptheywood — CHANGES_REQUESTED** [review]
The `twitter:creator` meta tag seems to be getting set incorrectly, i.e. it uses the author rather than the twitter username. 

```
<meta name="twitter:creator" content="@Robert (Bob) Turner" />
<meta name="twitter:creator" content="@Mozhgan Kabiri Chimeh" />
```

When according to the [twitter docs](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup) it should be an actual twitter username 
 
> `twitter:creator`
> 
> @username of content creator
> 
> Used with summary_large_image cards

**Comment by ptheywood** [comment]
https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#author-information

Seems to be the appropriate docs from the jekyll plugin.

**Comment by Robadob** [comment]
> https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/advanced-usage.md#author-information
> 
> Seems to be the appropriate docs from the jekyll plugin.

adding `  twitter: mkchimeh` to the post didn't work, so I guess we may need to go the `data/authors.yml` route?

**Comment by davidwyld** [comment]
Okay, I've tried again by getting rid of `jekyll-seo-tag` and just writing my own `<meta>` tags into `default.html`, that should correct the twitter creator issue by setting it from the username set in `_config.yml` as well as setting a bunch of other `og` tags and twitter tags.

Hopefully that still results in a valid social card.

**Comment by ptheywood** [comment]
Should there be an empty `og:image` when the post doesn't have an explicit image specifed?

```
<meta property="og:image" content="" />
```
I.e. should that tag be wrapped in an `if`?

Additionally, should it be a releative path or an absolute path? I.e. for my locally hosted instance it's currenttly 
```
<meta property="og:image" content="/assets/images/best-practice-blog/stock_mesabymakers_unsplash.jpg" />
```
but should it be 
```
<meta property="og:image" content="http://localhost:4000/assets/images/best-practice-blog/stock_mesabymakers_unsplash.jpg" />
```

This should just be a mater of prepending the url with the correct `{% site.url %}` parameter (not 100% it's site.url off the top of my head.

**Comment by davidwyld** [comment]
Yup, didn't spot that. Have made the image URLs absolute and added `site.logo` from the `_config.yml` as the default image.

**Comment by davidwyld** [comment]
Okay, that should do the trick :crossed_fingers: 

Sorry for doing this really piecemeal, just working out what I'm doing.

**Pull request merged**
