### PR TITLE
new seminars

### PR DESCRIPTION
**Pull request by mozhgan-kch**

### CODE REVIEW

**Comment by drj11** [comment]
Can you please delete your branches now that they're merged.

**Comment by ptheywood** [comment]
@drj11 This is from @mozhgan-kch's forks master, rather than a branch on the main repo

**Comment by drj11** [comment]
I know that. And this branch was branched from a non-master commit in RSE-Sheffield.

**Comment by willfurnass** [comment]
Yay for getting Hannah S to agree to give a presentation - she'll be great.

**Pull request merged**
