### PR TITLE
Make slides and recordings more discoverable

### PR DESCRIPTION
**Pull request by bobturneruk**
Adds previous events to home page and makes it clear where slides and recordings are.

### CODE REVIEW

**Comment by bobturneruk** [comment]
Sorry this is a nightmare as my ide has done a load of formatting changes!

**Comment by bobturneruk** [comment]
Relevant bits are:

- _layouts/home.html line 141
- assets/js/main.js line 96

**Review by ptheywood — APPROVED** [review]
Your IDE has made some very questionable decisions with linebreaks and indent in some places IMO, so it might be worth disabling the autoformatting if you can to prevent this from happening from any / all future PR's you make, as it does make the diff a lot harder to actually parse. 

The actual changes to the website are decent though.

**Comment by bobturneruk** [comment]
Thanks @ptheywood - I will disable this annoying IDE functionality.

**Pull request merged**
