### PR TITLE
Add new logos to website

### PR DESCRIPTION
**Pull request by davidwyld**
This PR:
- Replaces the old logo files with fancy new ones.
- Moves all the logo files to `assets/images/logo` - _will this break any links?_ (I can't see any on the website, but maybe people have others?)
- Moves any unused or old logo type files to `assets/images/logo/old` - same Q as above.

### CODE REVIEW

**Comment by Robadob** [comment]
image
Screenshot David posted to slack.

**Comment by willfurnass** [comment]
Looks fab on Firefox on Linux @ 100% zoom; some aliasing with smaller logo on Chromium on Linux at 100% zoom but IMO not really an issue; not yet tested on mobile (but we should).

**Comment by willfurnass** [comment]
Also looks good on both Chrome and Firefox on Moto G5 phone (Android).

**Review by willfurnass — APPROVED** [review]

**Comment by davidwyld** [comment]
Not exactly what you mean I suspect, but testing with dev tools mobile view in firefox there is a very minor issue, when you scroll down, the top bar turns white, so you can't see the nice white border. But this doesn't really bother me.
</img></img>

**Comment by willfurnass** [comment]
image

Aliasing of smaller logo shown here.  I don't think it's significant.

**Comment by davidwyld** [comment]
I think this is because I copied the actual size of the previous image that was there, which is 75px square but diplayed at 45px. Could resize it?

Any better?
image

**Review by ptheywood — APPROVED** [review]

**Pull request merged**
