### PR TITLE
add favicons

### PR DESCRIPTION
**Pull request by davidwyld**
This PR adds several favicons for different platforms.
for example:
image

I've tested serving locally but haven't got my mirror working yet. Might be worth a test on @Robadob's mirror before deployment.

### CODE REVIEW

**Comment by bobturneruk** [comment]
I can try and build it locally - anything in particular I should be looking out for?

**Comment by davidwyld** [comment]
> I can try and build it locally - anything in particular I should be looking out for?

I guess just that the icon displays wherever you're serving it.

**Comment by bobturneruk** [comment]
I see the little icon on the tab! And I approve.

**Review by bobturneruk — APPROVED** [review]
Yay.

**Review by Robadob — APPROVED** [review]
Works for me: https://rse-mirror.robadob.org/

Might want @ptheywood's input to confirm whether you're doing favicons the right or wrong way, he's the web guy (to me). 🤷‍♂️

**Comment by davidwyld** [comment]
Sounds like this works on the mirror too. Going to merge.

**Pull request merged**
