### PR TITLE
Switch from moment.js to day.js 1.11.0

### PR DESCRIPTION
**Pull request by ptheywood**
This is a lighter weight library for date/time processing, with moment.js in maintenance mode. 

This is to address potential moment.js vulns highligted by dependabot (although the specific issue does not impact our use of moment.js)

### CODE REVIEW

**Review by bobturneruk — APPROVED** [review]
Looks great as far as I can tell, but it would be ideal if someone with a bit more javascript knowledge had a quick look. Thanks for getting to this so swiftly!

**Comment by ptheywood** [comment]
You can test the change works by building locally and opening the home page. 
If the events are ordered correctly, and separated into future and past events then the JS is behaving as intended. 

Admitidly that is not very throrough, and there are still slight issues in the logic re: events moving to previous after they have started but before they have finished, but that is a much more substatantial change to our events to have much better multi-day event support.

**Comment by ns-rse** [comment]
Don't know a great deal of Javascript but the changes make sense to my limited understanding.

**Comment by bobturneruk** [comment]
I have a slight lull, so I'll try a local build. Thanks for the extra info. @ptheywood .

**Comment by bobturneruk** [comment]
I've built it and all looks good. This should be merged @ptheywood. Thanks again.

**Pull request merged**
