### PR TITLE
add TUoS logo to header

### PR DESCRIPTION
**Pull request by davidwyld**
Addresses #248.

image

Sort of doesn't look great, but conforms to the university's visual identity as far as I understand.

### CODE REVIEW

**Comment by ptheywood** [comment]
Alternatively could place in the footer on every page (alongside the Contact Us section) and in the promo section on the homepage, over/under the RSE logo?

**Comment by Robadob** [comment]
@ptheywood Are you sure that complies with university visual identity rules?

**Comment by ptheywood** [comment]
> @ptheywood Are you sure that complies with university visual identity rules?

They don't seem to have any restircitons on positioning of the logo anymore, just lots of rules about not altering the logo in any way, or making it look bad (pixely) by making it too big.

**Comment by davidwyld** [comment]
Nothing that we're doing complies with the visual identity really. If you look for guidelines on positioning/sizing the uni logo it just says "don't make your own website", "don't make your own branding" etc..

**Comment by annakrystalli** [comment]
Seeing as nothing we are doing really fully complies, why don't we use the reversed primary logo 😜? It might look nicer?

image

**Comment by davidwyld** [comment]
Yeah I think that looks cool but I feel like we should at least try to comply a bit.. :shrug:

**Comment by annakrystalli** [comment]
No worries

**Review by willfurnass — APPROVED** [review]

**Comment by willfurnass** [comment]
@davidwilby Thanks for this.

**Pull request merged**
