### PR TITLE
Reschedule Parallelisation lunchbytes.

### PR DESCRIPTION
**Pull request by Robadob**
Not too sure how the redirect link thing in header works, but i'll assume it's fine to specify two if CI passes.

### CODE REVIEW

**Review by bobturneruk — APPROVED** [review]
Looks good. I don't understand the link issue you mention in your comment. Maybe @ptheywood has some insight?

**Comment by Robadob** [comment]
https://github.com/jekyll/jekyll-redirect-from
It should be fine.

**Comment by Robadob** [comment]
Having it now updated, it works but it's case sensitive.

https://rse.shef.ac.uk/events/LunchBytes-2022-01-13.html
Redirects to
https://rse.shef.ac.uk/events/lunchbytes-2021-12-02.html

https://rse.shef.ac.uk/events/lunchBytes-2022-01-13.html
is 404

**Comment by ptheywood** [comment]
I would have suggested renaming the file and redirecting from the old address to the new, but grand scheme it's not important. Given the filenames and URI's are all lowercase though the all lower form of redirects should also be included.

**Pull request merged**
