### PR TITLE
[Work in Progress] Infinity

### PR DESCRIPTION
**Pull request by drj11**
needs a picture for the social card

### CODE REVIEW

**Comment by willfurnass** [comment]
@drj11 Ready for review?

**Comment by drj11** [comment]
Yes, happy for @RSE-Sheffield/rse-team to review, and anyone else.

Still needs a picture before we merge and publish though.

**Comment by drj11** [comment]
Now has a picture (I think)

**Review by willfurnass — APPROVED** [review]
LGTM.  One minor point: when might it be useful to explicitly instantiate an inf float variable?

**Comment by drj11** [comment]
yeah, good question. not going to address in this blog post.

**Comment by willfurnass** [comment]
I guess the value to researchers is knowing about these different values and that they may want/need to test for them (`assert x != float("inf")`, `assert not np.any(np.isinf(my_array)`, `assert not np.any(np.isneginf(my_array)` etc).  What do you think to adding a note about such tests?

**Comment by Robadob** [comment]
Loosely related. Today Pete and I discovered that the JSON spec doesn't support NaN or Infinity.

RapidJSON library aborts mid export if it encounters one of these values (unless you enable to some write flag I can't get to build).

**Comment by drj11** [comment]
Ah, the JSON fact gets me every time. I've been told several times now, but I always forget. In Python it's controlled by the `allow_nan=` keyword argument, which defaults to `True`, hence allowing NaN and Inf in the JSON.

**Comment by drj11** [comment]
@willfurnass yes, I'll add some words about not being so scared of Infinity and what things you might do with them (which was sort of the whole point of the blog post now that I think about it).

**Comment by willfurnass** [comment]
@Robadob That's interesting and, I think, relevant, given that researchers need to be increasingly aware of JSON/YAML and web services.

**Comment by Robadob** [comment]
Yeah, when I was validating V9 Primage model I had a few cases where the JSON output was aborted mid file. Couldn't find a way to reproduce it (yay highly stochastic models). But then I had a huge bug in my implementation yesterday so one value was always NaN.

Serves me right for not reading the documentation, and checking the return value.

**Pull request closed without merging**
