### PR TITLE
License content under CC-BY-SA 4.0

### LINKED ISSUE #25: License for site material
[CC-BY](https://creativecommons.org/licenses/by/4.0/)?

Migrated from RSE-Sheffield/old_team_site_nikola#36

### PR DESCRIPTION
**Pull request by willfurnass**
Fixes #25

### CODE REVIEW

**Comment by bobturneruk** [comment]
Are we sure that we can license everything on here under this license e.g. university logo? Maybe I'm being pedantic...

**Comment by willfurnass** [comment]
"(excluding logos or where explicitly stated)" ?

**Comment by Robadob** [comment]
Maybe just exclude images/video from the license. E.g. if we have guest blog posts etc.

**Comment by bobturneruk** [comment]
I think your statement is fine @willfurnass. We just then need to be
careful to state if we use a stock photo or something.

On Thu, 22 Apr 2021 at 09:19, Robert Chisholm ***@***.***> wrote:
>
> Maybe just exclude images/video from the license. E.g. if we have guest blog posts etc.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub, or unsubscribe.



-- 
Robert (Bob) Turner
Research Software Engineering Team
University of Sheffield
https://rse.shef.ac.uk

Please do not feel any pressure to respond outside of your working
hours (whatever they are).

**Comment by willfurnass** [comment]
Okay, statement added.

**Pull request merged**
